### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by jmac48210** [daggerhart/openid-connect-generic#195] opened 2020-07-09 22:13 UTC
Have a query on the redirect. Everything has been working fine, up until recently when a session is created it is now redirecting to xyz.xyz/favicon.ico?session=1594458416 instead of the page that the sign in button was. We have had the plugin for two years, but now only getting this issue.

**Comment by ashtonlance** [comment] 2020-07-10 15:41
I'm having a similar issue where I'm being redirected to the homepage on login.

**Comment by jmac48210** [comment] 2020-07-12 21:33
> I'm having a similar issue where I'm being redirected to the homepage on login.

Did you click on the redirect  tick box? That is meant to take you back to the page that you were last on.

**Comment by ashtonlance** [comment] 2020-07-13 14:02
@jmac48210 I have that ticked -- however when I log in from a page that's not the home page it still redirects there when I login with my sso

**Comment by jmac48210** [comment] 2020-07-13 23:13
> @jmac48210 I have that ticked -- however when I log in from a page that's not the home page it still redirects there when I login with my sso

I am having a different issue, occassionally goes back to home page, but other times it is calling the favicon, and presenting a blank page. When you type in the url again, it shows that it is logged in. 

As I said previously, we had no issue for 2 years, now all of a sudden we are having the issue.

**Comment by daggerhart** [comment] 2020-07-14 11:37
@jmac48210  that is a really strange bug. Can you provide any logs for when the errors happen?

Any error messages you could provide would be helpful. We have a lot of messages enabled for logging, and it will help a lot to determine where things are going wrong in the auth flow.

**Comment by jmac48210** [comment] 2020-07-14 22:48
> @jmac48210 that is a really strange bug. Can you provide any logs for when the errors happen?
> 
> Any error messages you could provide would be helpful. We have a lot of messages enabled for logging, and it will help a lot to determine where things are going wrong in the auth flow.

This is the thing, it is not generating an error as it is recognising it as correct information.

We have two sites using the plugin, one site is working correctly the other site generates the issue described above.

I have updated to the latest plugin from 3.4 and same issue is occurring.

What I have noticed is it is taking a long time to login.



Type: login-successDate: 2020-07-14 22:46:34User: 0URI : /wp-admin/admin-ajax.php?action=openid-connect-authorize&code=&session_state=3gEFpM_IhnZ8M5ITE00BXjtx8O29k94f1dGV_5I8D2I=.yCVcIT&state=bd2a435e672e6bd2be833c1e84f33d25 | string(35) "Successful login for: 10071143 (20)"
-- | --
Type: request_userinfoDate: 2020-07-14 22:46:23User: 0URI : /wp-admin/admin-ajax.php?action=openid-connect-authorize&code=&session_state=3gEFpM_IhnZ8M5ITE00BXjtx8O29k94f1dGV_5I8D2I=.yCVcIT&state=bd2a435e672e6bd2be833c1e84f33d25 | string(43) "https://membership.psa.asn.au/sso/userinfo/"
Type: request_authentication_tokenDate: 2020-07-14 22:46:20User: 0URI : /wp-admin/admin-ajax.php?action=openid-connect-authorize&code=&session_state=3gEFpM_IhnZ8M5ITE00BXjtx8O29k94f1dGV_5I8D2I=.yCVcIT&state=bd2a435e672e6bd2be833c1e84f33d25 | string(40) "https://membership.psa.asn.au/sso/token/"
Type: make_authentication_urlDate: 2020-07-14 22:46:08User: 0URI : /psa_document/s_aw2012_1235c7928/ | string(254) "https://membership.psa.asn.au/sso/authorize/?response_type=code&scope=openid&client_id=3FHkmPykQi2l3ToIiW9l4GbdZI&state=07beae27ddc67744b4fe458da0672609&redirect_uri=https%3A%2F%2Fpsa.asn.au%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dopenid-connect-authorize"
Type: make_authentication_urlDate: 2020-07-14 22:45:59User: 0URI : /member-area/ | string(254) "https://membership.psa.asn.au/sso/authorize/?response_type=code&scope=openid&client_id=3FHkmPykQi2l3ToIiW9l4GbdZI&state=bd2a435e672e6bd2be833c1e84f33d25&redirect_uri=https%3A%2F%2Fpsa.asn.au%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dopenid-connect-authorize"

**Comment by jmac48210** [comment] 2020-07-15 22:25
> @jmac48210 that is a really strange bug. Can you provide any logs for when the errors happen?
> 
> Any error messages you could provide would be helpful. We have a lot of messages enabled for logging, and it will help a lot to determine where things are going wrong in the auth flow.

Hi Jonathan, there is no error message as it is recognising that it is logged in. Even the logs on the plugin page show the origin page.

What we are noticing though it is taking 13-17 secs to log in to the SSO page, then another delay back to wordpress.

Is it possible that this could be the cause?

**Comment by jmac48210** [comment] 2020-08-18 04:36
Anyone able to help with this at all????

**Comment by jmac48210** [comment] 2020-08-18 04:38
It will not redirect back to origin page after logging in at all. Just keeps going back to home page. User is logged in

**Comment by timnolte** [comment] 2020-08-25 02:15
@jmac48210 take a look at my notes here: https://github.com/daggerhart/openid-connect-generic/issues/207#issuecomment-676932131

Are you able to check into any of the questions I ask there?

**Comment by timnolte** [comment] 2020-08-25 02:21
Duplicate of #207

**Closed by timnolte** 2020-08-25 02:21 UTC
Labels: duplicate
