### ISSUE TITLE
logout url

### ISSUE THREAD

**Issue by kkplein** [daggerhart/openid-connect-generic#67] opened 2018-01-22 16:08 UTC
Hi,

We have openid-connect-generic running in combination with keycloak. Works very nicely, thank you very much!

One issue though: Logging out doesn't work properly:
After installing your plugin, the wordpress logout url has been changed into https://www.oursite.com/wp-login.php?loggedout=true

However, we had disabled wordpress default links, such as /wp-admin and /wp-login url (using the WP Cerber plugin, as a basic security measure) causing the logout link above to generate an error.

Without the openid-connect-generic plugin, the logout url goes to:
https://www.oursite.com/randomstring/?action=logout

Our login url, is also https://www.oursite.com/randomstring, and this works fine, also with the openid-connect-generic plugin activated.

So, can we somehow define a different logout url..?

**Comment by lliming** [comment] 2018-01-22 16:30
The settings panel provides a place to configure an "End session endpoint URL." I set mine to the logout URL provided by my OIDC identity provider and it works very well. (My OIDC IDP allows parameters to be included in the link that direct back to my site from the logout page, which is also a nice feature.)

If I understand correctly, not all IDPs provide a logout URL. I'd be surprised, however, if KeyCloak doesn't since they seem to offer just about every other bell & whistle!

**Comment by lliming** [comment] 2018-01-22 16:34
This might help?  http://www.keycloak.org/docs/3.2/securing_apps/topics/oidc/java/logout.html  

I haven't used KeyCloak myself, so I'm not sure how you'd obtain the parameters to the logout URL they suggest, but maybe you do.

**Comment by daggerhart** [comment] 2018-01-22 16:54
I'm looking into it and think I might have the issue roughly identified. 

In the plugin settings on my keycloak-testing site I have my *End Session Endpoint URL* set to `http://localhost:8080/auth/realms/master/protocol/openid-connect/logout`. This will get you logged out of keycloak when the user attempts to logout, but appended to that logout url is some hardcoded WP expectations. I think those hardcoded expectations are the issue.

Here is where we're adding a filter to the logout_redirect- https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client-wrapper.php#L51

Then the method called (with what I think is the problem)- https://github.com/daggerhart/openid-connect-generic/blob/dev/includes/openid-connect-generic-client-wrapper.php#L214

Again, I'm not positive this is exactly the problem, but seems related.  Any thoughts on how we can handle this in a generic way for everyone?

For some simple testing, I think you could add another filter to the `logout_redirect` event and try altering the url this plugin is creating. Doing that might spark some ideas. If no one else has a moment to do so, I will try to explore this more within the next few days.

@lliming Thanks for hopping in to help, all feedback is welcome!

**Comment by kkplein** [comment] 2018-01-22 17:05
Daggerhart: what you are saying sounds like our issue, yes.

Reading this (http://lists.jboss.org/pipermail/keycloak-user/2016-April/005675.html) I thought I could add a url to the logout endpoint, like: https://keycloak.oursite.com/auth/realms/ourrealm/protocol/openid-connect/logout?redirect_uri=https://www.ourexternalsite.com
But this does nothing.
I am no programmer, but willing to help/test in any way I can... Sorry that I cannot do more...

Will think a bit about what you're saying "For some simple testing, I think you could add another filter to the logout_redirect event and try altering the url this plugin is creating".

**Comment by kkplein** [comment] 2018-01-22 17:12
Noticed also in the keycloak event log, that the logout event is logged with a redirect uri like this:
"redirect_uri | https://www.oursite.com/wp-login.php?loggedout=true"
Which is NOT what I typed into the wordpress openid-connect-generic config. So, somewhere, something adds this redirect uri.

**Comment by pjeby** [comment] 2018-02-23 05:55
The issue is that WP Cerber is *not* filtering `logout_redirect`, so the default WP redirect URL is used.  You can fix this by either making your logout links use an explicit redirect location, or by getting the WP Cerber folks to fix their plugin so that `wp-login.php?loggedout=true` is replaced with the correct page.

The specific issue here is that Cerber filters `wp_redirect` so that any redirect to wp-login.php goes to the right URL.  But when using this plugin, the redirection isn't done by Wordpress: it's done by Keycloak.  So the URL doesn't get rewritten.

The needed change to Cerber is very minor; basically adding this line:

```php
add_filter('logout_redirect', 'cerber_redirect', 10, 2);
```
As there is an existing function (`cerber_redirect`) that does the necessary translation.  The above line can be added to your theme's `functions.php`, or to the Cerber plugin's `wp-cerber.php`.

I have not actually tested this, but I would expect it to fix your problem.  If it does, you should probably pass that along to Cerber's support team, referencing this discussion in general and this comment in particular.  :)

**Comment by daggerhart** [comment] 2018-11-03 15:29
Seems like a lot of good information here, but no clear direction for modifications to this plugin. I'm going to close the issue for now. Please feel free to re-open if there is some additional information that can lead to a fix in my end. Thanks

**Closed by daggerhart** 2018-11-03 15:29 UTC

**Comment by rohit-uf** [comment] 2022-09-13 07:53
Hi @daggerhart 
First of all, thank you for the great plugin. Works like a charm with keycloak.

## My Setup
- I have setup buddyboss plugin with wordpress and using keycloak for authentication

## Issue

I am facing the similar issue as @kkplein. When I logout from top right corner (Toolbar) my logout url is `http://localhost/ipassio_community_staging`.
